#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbBeach
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlgarveBeach")]
	public partial class BaseDeDadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientes(Clientes instance);
    partial void UpdateClientes(Clientes instance);
    partial void DeleteClientes(Clientes instance);
    partial void InsertConcelho(Concelho instance);
    partial void UpdateConcelho(Concelho instance);
    partial void DeleteConcelho(Concelho instance);
    partial void InsertFreguesias(Freguesias instance);
    partial void UpdateFreguesias(Freguesias instance);
    partial void DeleteFreguesias(Freguesias instance);
    partial void InsertHospedagem(Hospedagem instance);
    partial void UpdateHospedagem(Hospedagem instance);
    partial void DeleteHospedagem(Hospedagem instance);
    partial void InsertPraia(Praia instance);
    partial void UpdatePraia(Praia instance);
    partial void DeletePraia(Praia instance);
    partial void InsertRestaurantes(Restaurantes instance);
    partial void UpdateRestaurantes(Restaurantes instance);
    partial void DeleteRestaurantes(Restaurantes instance);
    #endregion
		
		public BaseDeDadosDataContext() : 
				base(global::DbBeach.Properties.Settings.Default.AlgarveBeachConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clientes> Clientes
		{
			get
			{
				return this.GetTable<Clientes>();
			}
		}
		
		public System.Data.Linq.Table<Concelho> Concelho
		{
			get
			{
				return this.GetTable<Concelho>();
			}
		}
		
		public System.Data.Linq.Table<Freguesias> Freguesias
		{
			get
			{
				return this.GetTable<Freguesias>();
			}
		}
		
		public System.Data.Linq.Table<Hospedagem> Hospedagem
		{
			get
			{
				return this.GetTable<Hospedagem>();
			}
		}
		
		public System.Data.Linq.Table<Praia> Praia
		{
			get
			{
				return this.GetTable<Praia>();
			}
		}
		
		public System.Data.Linq.Table<Restaurantes> Restaurantes
		{
			get
			{
				return this.GetTable<Restaurantes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDcliente;
		
		private string _Username;
		
		private string _Password;
		
		private string _PNome;
		
		private string _UNome;
		
		private string _EMail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDclienteChanging(int value);
    partial void OnIDclienteChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPNomeChanging(string value);
    partial void OnPNomeChanged();
    partial void OnUNomeChanging(string value);
    partial void OnUNomeChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    #endregion
		
		public Clientes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDcliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDcliente
		{
			get
			{
				return this._IDcliente;
			}
			set
			{
				if ((this._IDcliente != value))
				{
					this.OnIDclienteChanging(value);
					this.SendPropertyChanging();
					this._IDcliente = value;
					this.SendPropertyChanged("IDcliente");
					this.OnIDclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNome", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PNome
		{
			get
			{
				return this._PNome;
			}
			set
			{
				if ((this._PNome != value))
				{
					this.OnPNomeChanging(value);
					this.SendPropertyChanging();
					this._PNome = value;
					this.SendPropertyChanged("PNome");
					this.OnPNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNome", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UNome
		{
			get
			{
				return this._UNome;
			}
			set
			{
				if ((this._UNome != value))
				{
					this.OnUNomeChanging(value);
					this.SendPropertyChanging();
					this._UNome = value;
					this.SendPropertyChanged("UNome");
					this.OnUNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Concelho")]
	public partial class Concelho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDconcelho;
		
		private string _NomeConcelho;
		
		private EntitySet<Freguesias> _Freguesias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDconcelhoChanging(int value);
    partial void OnIDconcelhoChanged();
    partial void OnNomeConcelhoChanging(string value);
    partial void OnNomeConcelhoChanged();
    #endregion
		
		public Concelho()
		{
			this._Freguesias = new EntitySet<Freguesias>(new Action<Freguesias>(this.attach_Freguesias), new Action<Freguesias>(this.detach_Freguesias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDconcelho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDconcelho
		{
			get
			{
				return this._IDconcelho;
			}
			set
			{
				if ((this._IDconcelho != value))
				{
					this.OnIDconcelhoChanging(value);
					this.SendPropertyChanging();
					this._IDconcelho = value;
					this.SendPropertyChanged("IDconcelho");
					this.OnIDconcelhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeConcelho", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NomeConcelho
		{
			get
			{
				return this._NomeConcelho;
			}
			set
			{
				if ((this._NomeConcelho != value))
				{
					this.OnNomeConcelhoChanging(value);
					this.SendPropertyChanging();
					this._NomeConcelho = value;
					this.SendPropertyChanged("NomeConcelho");
					this.OnNomeConcelhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Concelho_Freguesias", Storage="_Freguesias", ThisKey="IDconcelho", OtherKey="IDconcelho")]
		public EntitySet<Freguesias> Freguesias
		{
			get
			{
				return this._Freguesias;
			}
			set
			{
				this._Freguesias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Freguesias(Freguesias entity)
		{
			this.SendPropertyChanging();
			entity.Concelho = this;
		}
		
		private void detach_Freguesias(Freguesias entity)
		{
			this.SendPropertyChanging();
			entity.Concelho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Freguesias")]
	public partial class Freguesias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDfreguesia;
		
		private int _IDconcelho;
		
		private string _NomeFreguesia;
		
		private EntitySet<Praia> _Praia;
		
		private EntityRef<Concelho> _Concelho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDfreguesiaChanging(int value);
    partial void OnIDfreguesiaChanged();
    partial void OnIDconcelhoChanging(int value);
    partial void OnIDconcelhoChanged();
    partial void OnNomeFreguesiaChanging(string value);
    partial void OnNomeFreguesiaChanged();
    #endregion
		
		public Freguesias()
		{
			this._Praia = new EntitySet<Praia>(new Action<Praia>(this.attach_Praia), new Action<Praia>(this.detach_Praia));
			this._Concelho = default(EntityRef<Concelho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDfreguesia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDfreguesia
		{
			get
			{
				return this._IDfreguesia;
			}
			set
			{
				if ((this._IDfreguesia != value))
				{
					this.OnIDfreguesiaChanging(value);
					this.SendPropertyChanging();
					this._IDfreguesia = value;
					this.SendPropertyChanged("IDfreguesia");
					this.OnIDfreguesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDconcelho", DbType="Int NOT NULL")]
		public int IDconcelho
		{
			get
			{
				return this._IDconcelho;
			}
			set
			{
				if ((this._IDconcelho != value))
				{
					if (this._Concelho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDconcelhoChanging(value);
					this.SendPropertyChanging();
					this._IDconcelho = value;
					this.SendPropertyChanged("IDconcelho");
					this.OnIDconcelhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeFreguesia", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string NomeFreguesia
		{
			get
			{
				return this._NomeFreguesia;
			}
			set
			{
				if ((this._NomeFreguesia != value))
				{
					this.OnNomeFreguesiaChanging(value);
					this.SendPropertyChanging();
					this._NomeFreguesia = value;
					this.SendPropertyChanged("NomeFreguesia");
					this.OnNomeFreguesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Freguesias_Praia", Storage="_Praia", ThisKey="IDfreguesia", OtherKey="IDfreguesia")]
		public EntitySet<Praia> Praia
		{
			get
			{
				return this._Praia;
			}
			set
			{
				this._Praia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Concelho_Freguesias", Storage="_Concelho", ThisKey="IDconcelho", OtherKey="IDconcelho", IsForeignKey=true)]
		public Concelho Concelho
		{
			get
			{
				return this._Concelho.Entity;
			}
			set
			{
				Concelho previousValue = this._Concelho.Entity;
				if (((previousValue != value) 
							|| (this._Concelho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Concelho.Entity = null;
						previousValue.Freguesias.Remove(this);
					}
					this._Concelho.Entity = value;
					if ((value != null))
					{
						value.Freguesias.Add(this);
						this._IDconcelho = value.IDconcelho;
					}
					else
					{
						this._IDconcelho = default(int);
					}
					this.SendPropertyChanged("Concelho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Praia(Praia entity)
		{
			this.SendPropertyChanging();
			entity.Freguesias = this;
		}
		
		private void detach_Praia(Praia entity)
		{
			this.SendPropertyChanging();
			entity.Freguesias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hospedagem")]
	public partial class Hospedagem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDhospe;
		
		private int _IDpraia;
		
		private string _NomeHospe;
		
		private string _MoradaHospe;
		
		private int _DistanPraiaH;
		
		private short _Classificacao;
		
		private System.Nullable<short> _Camping;
		
		private System.Nullable<int> _VotoPosH;
		
		private System.Nullable<int> _VotoNegH;
		
		private string _LinkH;
		
		private EntityRef<Praia> _Praia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDhospeChanging(int value);
    partial void OnIDhospeChanged();
    partial void OnIDpraiaChanging(int value);
    partial void OnIDpraiaChanged();
    partial void OnNomeHospeChanging(string value);
    partial void OnNomeHospeChanged();
    partial void OnMoradaHospeChanging(string value);
    partial void OnMoradaHospeChanged();
    partial void OnDistanPraiaHChanging(int value);
    partial void OnDistanPraiaHChanged();
    partial void OnClassificacaoChanging(short value);
    partial void OnClassificacaoChanged();
    partial void OnCampingChanging(System.Nullable<short> value);
    partial void OnCampingChanged();
    partial void OnVotoPosHChanging(System.Nullable<int> value);
    partial void OnVotoPosHChanged();
    partial void OnVotoNegHChanging(System.Nullable<int> value);
    partial void OnVotoNegHChanged();
    partial void OnLinkHChanging(string value);
    partial void OnLinkHChanged();
    #endregion
		
		public Hospedagem()
		{
			this._Praia = default(EntityRef<Praia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDhospe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDhospe
		{
			get
			{
				return this._IDhospe;
			}
			set
			{
				if ((this._IDhospe != value))
				{
					this.OnIDhospeChanging(value);
					this.SendPropertyChanging();
					this._IDhospe = value;
					this.SendPropertyChanged("IDhospe");
					this.OnIDhospeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpraia", DbType="Int NOT NULL")]
		public int IDpraia
		{
			get
			{
				return this._IDpraia;
			}
			set
			{
				if ((this._IDpraia != value))
				{
					if (this._Praia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDpraiaChanging(value);
					this.SendPropertyChanging();
					this._IDpraia = value;
					this.SendPropertyChanged("IDpraia");
					this.OnIDpraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeHospe", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeHospe
		{
			get
			{
				return this._NomeHospe;
			}
			set
			{
				if ((this._NomeHospe != value))
				{
					this.OnNomeHospeChanging(value);
					this.SendPropertyChanging();
					this._NomeHospe = value;
					this.SendPropertyChanged("NomeHospe");
					this.OnNomeHospeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoradaHospe", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MoradaHospe
		{
			get
			{
				return this._MoradaHospe;
			}
			set
			{
				if ((this._MoradaHospe != value))
				{
					this.OnMoradaHospeChanging(value);
					this.SendPropertyChanging();
					this._MoradaHospe = value;
					this.SendPropertyChanged("MoradaHospe");
					this.OnMoradaHospeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanPraiaH", DbType="Int NOT NULL")]
		public int DistanPraiaH
		{
			get
			{
				return this._DistanPraiaH;
			}
			set
			{
				if ((this._DistanPraiaH != value))
				{
					this.OnDistanPraiaHChanging(value);
					this.SendPropertyChanging();
					this._DistanPraiaH = value;
					this.SendPropertyChanged("DistanPraiaH");
					this.OnDistanPraiaHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classificacao", DbType="SmallInt NOT NULL")]
		public short Classificacao
		{
			get
			{
				return this._Classificacao;
			}
			set
			{
				if ((this._Classificacao != value))
				{
					this.OnClassificacaoChanging(value);
					this.SendPropertyChanging();
					this._Classificacao = value;
					this.SendPropertyChanged("Classificacao");
					this.OnClassificacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camping", DbType="SmallInt")]
		public System.Nullable<short> Camping
		{
			get
			{
				return this._Camping;
			}
			set
			{
				if ((this._Camping != value))
				{
					this.OnCampingChanging(value);
					this.SendPropertyChanging();
					this._Camping = value;
					this.SendPropertyChanged("Camping");
					this.OnCampingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoPosH", DbType="Int")]
		public System.Nullable<int> VotoPosH
		{
			get
			{
				return this._VotoPosH;
			}
			set
			{
				if ((this._VotoPosH != value))
				{
					this.OnVotoPosHChanging(value);
					this.SendPropertyChanging();
					this._VotoPosH = value;
					this.SendPropertyChanged("VotoPosH");
					this.OnVotoPosHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoNegH", DbType="Int")]
		public System.Nullable<int> VotoNegH
		{
			get
			{
				return this._VotoNegH;
			}
			set
			{
				if ((this._VotoNegH != value))
				{
					this.OnVotoNegHChanging(value);
					this.SendPropertyChanging();
					this._VotoNegH = value;
					this.SendPropertyChanged("VotoNegH");
					this.OnVotoNegHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkH", DbType="VarChar(255)")]
		public string LinkH
		{
			get
			{
				return this._LinkH;
			}
			set
			{
				if ((this._LinkH != value))
				{
					this.OnLinkHChanging(value);
					this.SendPropertyChanging();
					this._LinkH = value;
					this.SendPropertyChanged("LinkH");
					this.OnLinkHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Praia_Hospedagem", Storage="_Praia", ThisKey="IDpraia", OtherKey="IDpraia", IsForeignKey=true)]
		public Praia Praia
		{
			get
			{
				return this._Praia.Entity;
			}
			set
			{
				Praia previousValue = this._Praia.Entity;
				if (((previousValue != value) 
							|| (this._Praia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Praia.Entity = null;
						previousValue.Hospedagem.Remove(this);
					}
					this._Praia.Entity = value;
					if ((value != null))
					{
						value.Hospedagem.Add(this);
						this._IDpraia = value.IDpraia;
					}
					else
					{
						this._IDpraia = default(int);
					}
					this.SendPropertyChanged("Praia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Praia")]
	public partial class Praia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDpraia;
		
		private int _IDfreguesia;
		
		private string _NomePraia;
		
		private string _MoradaPraia;
		
		private int _ExtensaoPraia;
		
		private short _BandeiraAzul;
		
		private short _TemperaturaAgua;
		
		private short _AcessoSoBarco;
		
		private System.Nullable<int> _VotoPosP;
		
		private System.Nullable<int> _VotoNegP;
		
		private string _LinkP;
		
		private EntitySet<Hospedagem> _Hospedagem;
		
		private EntitySet<Restaurantes> _Restaurantes;
		
		private EntityRef<Freguesias> _Freguesias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDpraiaChanging(int value);
    partial void OnIDpraiaChanged();
    partial void OnIDfreguesiaChanging(int value);
    partial void OnIDfreguesiaChanged();
    partial void OnNomePraiaChanging(string value);
    partial void OnNomePraiaChanged();
    partial void OnMoradaPraiaChanging(string value);
    partial void OnMoradaPraiaChanged();
    partial void OnExtensaoPraiaChanging(int value);
    partial void OnExtensaoPraiaChanged();
    partial void OnBandeiraAzulChanging(short value);
    partial void OnBandeiraAzulChanged();
    partial void OnTemperaturaAguaChanging(short value);
    partial void OnTemperaturaAguaChanged();
    partial void OnAcessoSoBarcoChanging(short value);
    partial void OnAcessoSoBarcoChanged();
    partial void OnVotoPosPChanging(System.Nullable<int> value);
    partial void OnVotoPosPChanged();
    partial void OnVotoNegPChanging(System.Nullable<int> value);
    partial void OnVotoNegPChanged();
    partial void OnLinkPChanging(string value);
    partial void OnLinkPChanged();
    #endregion
		
		public Praia()
		{
			this._Hospedagem = new EntitySet<Hospedagem>(new Action<Hospedagem>(this.attach_Hospedagem), new Action<Hospedagem>(this.detach_Hospedagem));
			this._Restaurantes = new EntitySet<Restaurantes>(new Action<Restaurantes>(this.attach_Restaurantes), new Action<Restaurantes>(this.detach_Restaurantes));
			this._Freguesias = default(EntityRef<Freguesias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpraia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDpraia
		{
			get
			{
				return this._IDpraia;
			}
			set
			{
				if ((this._IDpraia != value))
				{
					this.OnIDpraiaChanging(value);
					this.SendPropertyChanging();
					this._IDpraia = value;
					this.SendPropertyChanged("IDpraia");
					this.OnIDpraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDfreguesia", DbType="Int NOT NULL")]
		public int IDfreguesia
		{
			get
			{
				return this._IDfreguesia;
			}
			set
			{
				if ((this._IDfreguesia != value))
				{
					if (this._Freguesias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDfreguesiaChanging(value);
					this.SendPropertyChanging();
					this._IDfreguesia = value;
					this.SendPropertyChanged("IDfreguesia");
					this.OnIDfreguesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePraia", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NomePraia
		{
			get
			{
				return this._NomePraia;
			}
			set
			{
				if ((this._NomePraia != value))
				{
					this.OnNomePraiaChanging(value);
					this.SendPropertyChanging();
					this._NomePraia = value;
					this.SendPropertyChanged("NomePraia");
					this.OnNomePraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoradaPraia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MoradaPraia
		{
			get
			{
				return this._MoradaPraia;
			}
			set
			{
				if ((this._MoradaPraia != value))
				{
					this.OnMoradaPraiaChanging(value);
					this.SendPropertyChanging();
					this._MoradaPraia = value;
					this.SendPropertyChanged("MoradaPraia");
					this.OnMoradaPraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensaoPraia", DbType="Int NOT NULL")]
		public int ExtensaoPraia
		{
			get
			{
				return this._ExtensaoPraia;
			}
			set
			{
				if ((this._ExtensaoPraia != value))
				{
					this.OnExtensaoPraiaChanging(value);
					this.SendPropertyChanging();
					this._ExtensaoPraia = value;
					this.SendPropertyChanged("ExtensaoPraia");
					this.OnExtensaoPraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandeiraAzul", DbType="SmallInt NOT NULL")]
		public short BandeiraAzul
		{
			get
			{
				return this._BandeiraAzul;
			}
			set
			{
				if ((this._BandeiraAzul != value))
				{
					this.OnBandeiraAzulChanging(value);
					this.SendPropertyChanging();
					this._BandeiraAzul = value;
					this.SendPropertyChanged("BandeiraAzul");
					this.OnBandeiraAzulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemperaturaAgua", DbType="SmallInt NOT NULL")]
		public short TemperaturaAgua
		{
			get
			{
				return this._TemperaturaAgua;
			}
			set
			{
				if ((this._TemperaturaAgua != value))
				{
					this.OnTemperaturaAguaChanging(value);
					this.SendPropertyChanging();
					this._TemperaturaAgua = value;
					this.SendPropertyChanged("TemperaturaAgua");
					this.OnTemperaturaAguaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcessoSoBarco", DbType="SmallInt NOT NULL")]
		public short AcessoSoBarco
		{
			get
			{
				return this._AcessoSoBarco;
			}
			set
			{
				if ((this._AcessoSoBarco != value))
				{
					this.OnAcessoSoBarcoChanging(value);
					this.SendPropertyChanging();
					this._AcessoSoBarco = value;
					this.SendPropertyChanged("AcessoSoBarco");
					this.OnAcessoSoBarcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoPosP", DbType="Int")]
		public System.Nullable<int> VotoPosP
		{
			get
			{
				return this._VotoPosP;
			}
			set
			{
				if ((this._VotoPosP != value))
				{
					this.OnVotoPosPChanging(value);
					this.SendPropertyChanging();
					this._VotoPosP = value;
					this.SendPropertyChanged("VotoPosP");
					this.OnVotoPosPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoNegP", DbType="Int")]
		public System.Nullable<int> VotoNegP
		{
			get
			{
				return this._VotoNegP;
			}
			set
			{
				if ((this._VotoNegP != value))
				{
					this.OnVotoNegPChanging(value);
					this.SendPropertyChanging();
					this._VotoNegP = value;
					this.SendPropertyChanged("VotoNegP");
					this.OnVotoNegPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkP", DbType="VarChar(255)")]
		public string LinkP
		{
			get
			{
				return this._LinkP;
			}
			set
			{
				if ((this._LinkP != value))
				{
					this.OnLinkPChanging(value);
					this.SendPropertyChanging();
					this._LinkP = value;
					this.SendPropertyChanged("LinkP");
					this.OnLinkPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Praia_Hospedagem", Storage="_Hospedagem", ThisKey="IDpraia", OtherKey="IDpraia")]
		public EntitySet<Hospedagem> Hospedagem
		{
			get
			{
				return this._Hospedagem;
			}
			set
			{
				this._Hospedagem.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Praia_Restaurantes", Storage="_Restaurantes", ThisKey="IDpraia", OtherKey="IDpraia")]
		public EntitySet<Restaurantes> Restaurantes
		{
			get
			{
				return this._Restaurantes;
			}
			set
			{
				this._Restaurantes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Freguesias_Praia", Storage="_Freguesias", ThisKey="IDfreguesia", OtherKey="IDfreguesia", IsForeignKey=true)]
		public Freguesias Freguesias
		{
			get
			{
				return this._Freguesias.Entity;
			}
			set
			{
				Freguesias previousValue = this._Freguesias.Entity;
				if (((previousValue != value) 
							|| (this._Freguesias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Freguesias.Entity = null;
						previousValue.Praia.Remove(this);
					}
					this._Freguesias.Entity = value;
					if ((value != null))
					{
						value.Praia.Add(this);
						this._IDfreguesia = value.IDfreguesia;
					}
					else
					{
						this._IDfreguesia = default(int);
					}
					this.SendPropertyChanged("Freguesias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hospedagem(Hospedagem entity)
		{
			this.SendPropertyChanging();
			entity.Praia = this;
		}
		
		private void detach_Hospedagem(Hospedagem entity)
		{
			this.SendPropertyChanging();
			entity.Praia = null;
		}
		
		private void attach_Restaurantes(Restaurantes entity)
		{
			this.SendPropertyChanging();
			entity.Praia = this;
		}
		
		private void detach_Restaurantes(Restaurantes entity)
		{
			this.SendPropertyChanging();
			entity.Praia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Restaurantes")]
	public partial class Restaurantes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDrest;
		
		private int _IDpraia;
		
		private string _NomeRest;
		
		private string _MoradaRest;
		
		private int _DistanPraiaR;
		
		private System.Nullable<int> _VotoPosR;
		
		private System.Nullable<int> _VotoNegR;
		
		private string _LinkR;
		
		private EntityRef<Praia> _Praia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDrestChanging(int value);
    partial void OnIDrestChanged();
    partial void OnIDpraiaChanging(int value);
    partial void OnIDpraiaChanged();
    partial void OnNomeRestChanging(string value);
    partial void OnNomeRestChanged();
    partial void OnMoradaRestChanging(string value);
    partial void OnMoradaRestChanged();
    partial void OnDistanPraiaRChanging(int value);
    partial void OnDistanPraiaRChanged();
    partial void OnVotoPosRChanging(System.Nullable<int> value);
    partial void OnVotoPosRChanged();
    partial void OnVotoNegRChanging(System.Nullable<int> value);
    partial void OnVotoNegRChanged();
    partial void OnLinkRChanging(string value);
    partial void OnLinkRChanged();
    #endregion
		
		public Restaurantes()
		{
			this._Praia = default(EntityRef<Praia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDrest", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDrest
		{
			get
			{
				return this._IDrest;
			}
			set
			{
				if ((this._IDrest != value))
				{
					this.OnIDrestChanging(value);
					this.SendPropertyChanging();
					this._IDrest = value;
					this.SendPropertyChanged("IDrest");
					this.OnIDrestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpraia", DbType="Int NOT NULL")]
		public int IDpraia
		{
			get
			{
				return this._IDpraia;
			}
			set
			{
				if ((this._IDpraia != value))
				{
					if (this._Praia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDpraiaChanging(value);
					this.SendPropertyChanging();
					this._IDpraia = value;
					this.SendPropertyChanged("IDpraia");
					this.OnIDpraiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeRest", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeRest
		{
			get
			{
				return this._NomeRest;
			}
			set
			{
				if ((this._NomeRest != value))
				{
					this.OnNomeRestChanging(value);
					this.SendPropertyChanging();
					this._NomeRest = value;
					this.SendPropertyChanged("NomeRest");
					this.OnNomeRestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoradaRest", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MoradaRest
		{
			get
			{
				return this._MoradaRest;
			}
			set
			{
				if ((this._MoradaRest != value))
				{
					this.OnMoradaRestChanging(value);
					this.SendPropertyChanging();
					this._MoradaRest = value;
					this.SendPropertyChanged("MoradaRest");
					this.OnMoradaRestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanPraiaR", DbType="Int NOT NULL")]
		public int DistanPraiaR
		{
			get
			{
				return this._DistanPraiaR;
			}
			set
			{
				if ((this._DistanPraiaR != value))
				{
					this.OnDistanPraiaRChanging(value);
					this.SendPropertyChanging();
					this._DistanPraiaR = value;
					this.SendPropertyChanged("DistanPraiaR");
					this.OnDistanPraiaRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoPosR", DbType="Int")]
		public System.Nullable<int> VotoPosR
		{
			get
			{
				return this._VotoPosR;
			}
			set
			{
				if ((this._VotoPosR != value))
				{
					this.OnVotoPosRChanging(value);
					this.SendPropertyChanging();
					this._VotoPosR = value;
					this.SendPropertyChanged("VotoPosR");
					this.OnVotoPosRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VotoNegR", DbType="Int")]
		public System.Nullable<int> VotoNegR
		{
			get
			{
				return this._VotoNegR;
			}
			set
			{
				if ((this._VotoNegR != value))
				{
					this.OnVotoNegRChanging(value);
					this.SendPropertyChanging();
					this._VotoNegR = value;
					this.SendPropertyChanged("VotoNegR");
					this.OnVotoNegRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkR", DbType="VarChar(255)")]
		public string LinkR
		{
			get
			{
				return this._LinkR;
			}
			set
			{
				if ((this._LinkR != value))
				{
					this.OnLinkRChanging(value);
					this.SendPropertyChanging();
					this._LinkR = value;
					this.SendPropertyChanged("LinkR");
					this.OnLinkRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Praia_Restaurantes", Storage="_Praia", ThisKey="IDpraia", OtherKey="IDpraia", IsForeignKey=true)]
		public Praia Praia
		{
			get
			{
				return this._Praia.Entity;
			}
			set
			{
				Praia previousValue = this._Praia.Entity;
				if (((previousValue != value) 
							|| (this._Praia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Praia.Entity = null;
						previousValue.Restaurantes.Remove(this);
					}
					this._Praia.Entity = value;
					if ((value != null))
					{
						value.Restaurantes.Add(this);
						this._IDpraia = value.IDpraia;
					}
					else
					{
						this._IDpraia = default(int);
					}
					this.SendPropertyChanged("Praia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
